"""create_labor_material_matches

Revision ID: 7081042367e0
Revises: b35dc65d779f
Create Date: 2026-05-17 06:06:52.822068
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7081042367e0'
down_revision: Union[str, Sequence[str], None] = 'b35dc65d779f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labor_material_matches',
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('labor_partner_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_role', sa.String(length=255), nullable=True),
    sa.Column('can_bid_as_prime', sa.Boolean(), nullable=True),
    sa.Column('can_bid_as_sub', sa.Boolean(), nullable=True),
    sa.Column('material_only_possible', sa.Boolean(), nullable=True),
    sa.Column('supply_and_install_possible', sa.Boolean(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('estimated_margin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bid_opportunities.id'], ),
    sa.ForeignKeyConstraint(['labor_partner_id'], ['labor_partners.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['material_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labor_material_matches')
    # ### end Alembic commands ###
