"""create_bid_opportunities

Revision ID: 7b78f728d2cd
Revises: f0a8f740f92d
Create Date: 2026-05-17 05:51:47.158030
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b78f728d2cd'
down_revision: Union[str, Sequence[str], None] = 'f0a8f740f92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_opportunities',
    sa.Column('bid_name', sa.String(length=255), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid_link', sa.Text(), nullable=True),
    sa.Column('bid_type', sa.Enum('material_only', 'labor_only', 'supply_and_install', 'full_rehab_unit_turnover', 'commercial_casework_millwork', 'unknown', name='bid_type', native_enum=False), nullable=False),
    sa.Column('scope_summary', sa.Text(), nullable=True),
    sa.Column('material_required', sa.Boolean(), nullable=True),
    sa.Column('labor_required', sa.Boolean(), nullable=True),
    sa.Column('license_required', sa.Boolean(), nullable=True),
    sa.Column('bond_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('workers_comp_required', sa.Boolean(), nullable=True),
    sa.Column('prevailing_wage', sa.Boolean(), nullable=True),
    sa.Column('site_visit_required', sa.Boolean(), nullable=True),
    sa.Column('estimated_contract_size', sa.String(length=255), nullable=True),
    sa.Column('estimated_kitchens_units', sa.Integer(), nullable=True),
    sa.Column('suggested_bid_range', sa.String(length=255), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'reviewing', 'need_partner', 'pricing', 'submitted', 'won', 'lost', 'skipped', name='bid_status', native_enum=False), server_default='new', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_partners',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('service_area', sa.String(length=255), nullable=True),
    sa.Column('trade_type', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_status', sa.String(length=100), nullable=True),
    sa.Column('insurance_status', sa.String(length=100), nullable=True),
    sa.Column('bonding_status', sa.String(length=100), nullable=True),
    sa.Column('workers_comp_status', sa.String(length=100), nullable=True),
    sa.Column('public_housing_experience', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('multifamily_experience', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('prevailing_wage_experience', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('occupied_unit_experience', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('capacity_per_week', sa.Integer(), nullable=True),
    sa.Column('photos_portfolio_link', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('agreement_signed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', 'rejected', name='partner_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labor_partners')
    op.drop_table('bid_opportunities')
    # ### end Alembic commands ###
