"""create_material_suppliers

Revision ID: b35dc65d779f
Revises: 7b78f728d2cd
Create Date: 2026-05-17 06:00:56.465548
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b35dc65d779f'
down_revision: Union[str, Sequence[str], None] = '7b78f728d2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_suppliers',
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('supplier_type', sa.Enum('local_cabinet_wholesaler', 'rta_supplier', 'imported_manufacturer', 'countertop_fabricator', 'vanity_supplier', 'hardware_supplier', 'plumbing_appliance_supplier', 'other', name='supplier_type', native_enum=False), nullable=False),
    sa.Column('product_categories', sa.Text(), nullable=True),
    sa.Column('service_area', sa.String(length=255), nullable=True),
    sa.Column('ships_nationwide', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('minimum_order', sa.String(length=255), nullable=True),
    sa.Column('lead_time', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('warranty', sa.Text(), nullable=True),
    sa.Column('sample_availability', sa.String(length=255), nullable=True),
    sa.Column('bulk_pricing', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('government_experience', sa.Text(), nullable=True),
    sa.Column('product_catalog_link', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'pending', 'rejected', name='material_supplier_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_suppliers')
    # ### end Alembic commands ###
